requirements.txt

Standard for pip (Python’s package manager).

Lists packages + versions.

Example:
Flask==2.2.2
pandas==1.5.3
openpyxl==3.1.2   # needed for Excel

Flask==2.2.2
pandas==1.5.3
openpyxl==3.1.2   # needed for Excel

Install with:
pip install -r requirements.txt

environment.yml

Standard for conda (Anaconda / Miniconda environments).

Can specify:

Python version

Channels (e.g., conda-forge)

Both pip and conda dependencies

Example:

name: population-api
dependencies:
  - python=3.10
  - flask=2.2.2
  - pandas=1.5.3
  - openpyxl=3.1.2
  - pip
  - pip:
      - gunicorn   # extra pip-only packages

Create env with:
conda env create -f environment.yml
conda activate population-api

lightweight API deployment → use requirements.txt.

complex dependencies (maybe Jupyter, numpy, etc.) → use environment.yml.
